from selenium import webdriver
from selenium.webdriver.common.keys import Keys
print("test case menu 'let's talk tea' started")
driver = webdriver.Chrome(r"C:\Users\fadhila\Downloads\chromedriver_win32\chromedriver.exe")
print("open browser & go to http://www.practiceselenium.com/")
driver.get("http://www.practiceselenium.com/")
print("click menu 'let's talk tea'")
driver.find_element_by_xpath("//*[@id='wsb-nav-00000000-0000-0000-0000-000450914915']/ul/li[4]/a").click()
print("input form 'Send Us Email'")
driver.find_element_by_tag_name("h2")
print("input field name with 'fadhila'")
driver.find_element_by_name('name').send_keys("fadhila")
print("input field email with 'fadhilara12@gmail.com'")
driver.find_element_by_name('email').send_keys("fadhilara12@gmail.com")
print("input field subject with 'subject 123'")
driver.find_element_by_name('subject').send_keys("subject 123")
print("input field message with 'subject 123'")
driver.find_element_by_name('message').send_keys("message 123")
print("click button 'submit'")
driver.find_element_by_xpath("//*[@id='form_78ea690540a24bd8b9dcfbf99e999fea']/div[1]/div[5]/input")
#print("close browser")
#driver.close()
print("test case menu 'let's talk tea' successfully completed")